### ISSUE TITLE
Add keywords to transform metadata to quickly find them

### ISSUE THREAD

**Issue by mattcasters** [atolcd/hop-gis-plugins#3]
Typing in GIS or Geospatial in an action dialog should find all the plugins in this project

**Comment by cvagner** [comment]
Thanks a lot @mattcasters !

I merged your pull request and just had a commit with some imports reorganization to conform our formatting requirements.
You can check it with `mvn spotless:check` and apply formatting with `mvn spotless:apply`.

Thank you for your advice and your responsiveness!
