### ISSUE TITLE
[Feature] Allow Metadata injection in GIS File Input transform

### ISSUE THREAD

**Issue by scali** [atolcd/hop-gis-plugins#5]
**What would you like to be added:**

 The transform **GIS File Input** doesn't support Metadata injection, especially **Filename** parameter, that could be very usefull to write reusable pipelines.

The feature would be very similar of what is actually possible for transforms like **CSV file input** or **Text file input**

**Alternatives:**

No alternative is possible if we want to use metadata injection

**Has the feature been requested before?**

No

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by cvagner** [comment]
Thanks @scali. Sure it would be nice !

**Comment by cvagner** [comment]
Your commits are merged. Thanks you @scali !
